version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:20.19.0
    resource_class: small

jobs:
  check-docker:
    executor: node
    steps:
      - run:
          name: Install Yarn
          command: |
            yarn workspace phoma-scripts install --immutable

      # - run:
      #     name: List Docker Containers
      #     command: |
      #       docker compose version

workflows:
  docker-check-workflow:
    jobs:
      - check-docker