version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:22.21
    resource_class: small

jobs:
  test_remote_docker:
    executor: node
    steps:
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          name: Check Docker Version
          command: docker --version

workflows:
  docker-check-workflow:
    jobs:
      - test_remote_docker